config:
  irc:
    nick: ele-standup-bot
    user_name: ele-standup-bot
    real_name: 'Ele Standup Bot'
    server: irc.freenode.net
    port: 7000
    ssl: true
    channels:
      definitions:
      - { name: '#funfunfun' }
      - { name: '#funfunfun2', password: 'mypass' }
      publish:
      - '#funfunfun'
      remind:
      - '#funfunfun'
      - '#funfunfun2'
  members_dir: 'members'
  members:
    - dcwangmit01
    - gdusbabek
    - rphillips
    - kc5tja
    - pquerna
    - dispalt
    - rch
    - dcwangmit01
    - lakspace
    - arreyder
    - jburkhart
    - ifup
    - JasonF
    - jirwin
    - russell_h
  domain: 'standup.cm.rax.io'
  # A few default reminder times
  # All times are set in UTC
  # early reminder: 10:45am PST monday through friday
  # due reminder: 11:00am PST monday through friday
  # late reminder: 2:30pm PST monday through friday
  # deadline reminder: 6:00pm PST monday through friday
  timers: {
    earlyReminder: '0 45 17 * * 1-5',
    dueReminder: '0 0 18 * * 1-5',
    lateReminder: '0 30 21 * * 1-5',
    deadlineReminder: '0 0 1 * * 2-6'
  }
